# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/plasma-framework': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kitemmodels': '@latest'
